[package]
name = "rivet"
version = "0.3.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
itertools = "0.14.0"
ratatui = "0.30.0"
rusqlite = "0.38.0"
unicode-width = "0.2.2"
