[package]
name = "rust-sqlite-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
itertools = "0.14.0"
ratatui = "0.30.0"
rusqlite = "0.38.0"
unicode-width = "0.2.2"
